{"name": "Unsuccessful login with invalid credentials", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\lclar\\Documents\\todoist - Selenium\\.venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lclar\\Documents\\todoist - Selenium\\.venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 57, in step_impl\n    assert context.login_page.get_error_message() == error_message\n"}, "steps": [{"name": "Given a web browser is at the todoist login page", "status": "passed", "start": 1722643355098, "stop": 1722643380629}, {"name": "When a user provides incorrect Todoist credentials and clicks on the Todoist login button", "status": "passed", "steps": [{"name": "Entering username: invalidUser1@gmail.com", "status": "passed", "start": 1722643380630, "stop": 1722643380810}, {"name": "Entering password", "status": "passed", "start": 1722643380811, "stop": 1722643380963}, {"name": "Clicking on login button", "status": "passed", "start": 1722643380963, "stop": 1722643381047}, {"name": "Entering username: invalidUser2@gmail.com", "status": "passed", "start": 1722643381047, "stop": 1722643381345}, {"name": "Entering password", "status": "passed", "start": 1722643381345, "stop": 1722643381546}, {"name": "Clicking on login button", "status": "passed", "start": 1722643381547, "stop": 1722643381686}], "attachments": [{"name": ".table", "source": "52b8de90-96a3-4ba1-b09b-2434a9761fdd-attachment.csv", "type": "text/csv"}], "start": 1722643380629, "stop": 1722643381686}, {"name": "Then the Todoist error message \"Invalid email or password.\" is displayed", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\lclar\\Documents\\todoist - Selenium\\.venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lclar\\Documents\\todoist - Selenium\\.venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 57, in step_impl\n    assert context.login_page.get_error_message() == error_message\n"}, "steps": [{"name": "Checking error message: Invalid email or password.", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"features\\steps\\login_steps.py\", line 57, in step_impl\n    assert context.login_page.get_error_message() == error_message\n"}, "start": 1722643381687, "stop": 1722643381722}], "start": 1722643381686, "stop": 1722643381723}], "start": 1722643355095, "stop": 1722643383792, "uuid": "dcf59d10-196c-4e5e-bb56-f918c453622d", "historyId": "ebd0fd2c49b770f03a8a924c9cc97ea2", "fullName": "Todoist Login: Unsuccessful login with invalid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Todoist Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}